{{ profile }}:
  target: dev
  outputs:
    dev:
      type: postgres
      host: {{ host }}
      port: {{ port }}
      dbname: {{ database }}
      schema: {{ db_schema }}
      user: {{ user }}
      password: {{ password }}
      threads: 4